// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/openziti/zrok/rest_model_zrok"
)

// OauthProvidersReader is a Reader for the OauthProviders structure.
type OauthProvidersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OauthProvidersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewOauthProvidersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /oauth/providers] oauthProviders", response, response.Code())
	}
}

// NewOauthProvidersOK creates a OauthProvidersOK with default headers values
func NewOauthProvidersOK() *OauthProvidersOK {
	return &OauthProvidersOK{}
}

/*
OauthProvidersOK describes a response with status code 200, with default header values.

list of OAuth providers
*/
type OauthProvidersOK struct {
	Payload []*rest_model_zrok.OauthProvider
}

// IsSuccess returns true when this oauth providers o k response has a 2xx status code
func (o *OauthProvidersOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this oauth providers o k response has a 3xx status code
func (o *OauthProvidersOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this oauth providers o k response has a 4xx status code
func (o *OauthProvidersOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this oauth providers o k response has a 5xx status code
func (o *OauthProvidersOK) IsServerError() bool {
	return false
}

// IsCode returns true when this oauth providers o k response a status code equal to that given
func (o *OauthProvidersOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the oauth providers o k response
func (o *OauthProvidersOK) Code() int {
	return 200
}

func (o *OauthProvidersOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /oauth/providers][%d] oauthProvidersOK %s", 200, payload)
}

func (o *OauthProvidersOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /oauth/providers][%d] oauthProvidersOK %s", 200, payload)
}

func (o *OauthProvidersOK) GetPayload() []*rest_model_zrok.OauthProvider {
	return o.Payload
}

func (o *OauthProvidersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
