// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewOauthCallbackParams creates a new OauthCallbackParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewOauthCallbackParams() *OauthCallbackParams {
	return &OauthCallbackParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewOauthCallbackParamsWithTimeout creates a new OauthCallbackParams object
// with the ability to set a timeout on a request.
func NewOauthCallbackParamsWithTimeout(timeout time.Duration) *OauthCallbackParams {
	return &OauthCallbackParams{
		timeout: timeout,
	}
}

// NewOauthCallbackParamsWithContext creates a new OauthCallbackParams object
// with the ability to set a context for a request.
func NewOauthCallbackParamsWithContext(ctx context.Context) *OauthCallbackParams {
	return &OauthCallbackParams{
		Context: ctx,
	}
}

// NewOauthCallbackParamsWithHTTPClient creates a new OauthCallbackParams object
// with the ability to set a custom HTTPClient for a request.
func NewOauthCallbackParamsWithHTTPClient(client *http.Client) *OauthCallbackParams {
	return &OauthCallbackParams{
		HTTPClient: client,
	}
}

/*
OauthCallbackParams contains all the parameters to send to the API endpoint

	for the oauth callback operation.

	Typically these are written to a http.Request.
*/
type OauthCallbackParams struct {

	// Code.
	Code string

	// Error.
	Error *string

	// Provider.
	Provider string

	// State.
	State string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the oauth callback params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OauthCallbackParams) WithDefaults() *OauthCallbackParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the oauth callback params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OauthCallbackParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the oauth callback params
func (o *OauthCallbackParams) WithTimeout(timeout time.Duration) *OauthCallbackParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the oauth callback params
func (o *OauthCallbackParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the oauth callback params
func (o *OauthCallbackParams) WithContext(ctx context.Context) *OauthCallbackParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the oauth callback params
func (o *OauthCallbackParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the oauth callback params
func (o *OauthCallbackParams) WithHTTPClient(client *http.Client) *OauthCallbackParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the oauth callback params
func (o *OauthCallbackParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCode adds the code to the oauth callback params
func (o *OauthCallbackParams) WithCode(code string) *OauthCallbackParams {
	o.SetCode(code)
	return o
}

// SetCode adds the code to the oauth callback params
func (o *OauthCallbackParams) SetCode(code string) {
	o.Code = code
}

// WithError adds the error to the oauth callback params
func (o *OauthCallbackParams) WithError(error *string) *OauthCallbackParams {
	o.SetError(error)
	return o
}

// SetError adds the error to the oauth callback params
func (o *OauthCallbackParams) SetError(error *string) {
	o.Error = error
}

// WithProvider adds the provider to the oauth callback params
func (o *OauthCallbackParams) WithProvider(provider string) *OauthCallbackParams {
	o.SetProvider(provider)
	return o
}

// SetProvider adds the provider to the oauth callback params
func (o *OauthCallbackParams) SetProvider(provider string) {
	o.Provider = provider
}

// WithState adds the state to the oauth callback params
func (o *OauthCallbackParams) WithState(state string) *OauthCallbackParams {
	o.SetState(state)
	return o
}

// SetState adds the state to the oauth callback params
func (o *OauthCallbackParams) SetState(state string) {
	o.State = state
}

// WriteToRequest writes these params to a swagger request
func (o *OauthCallbackParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param code
	qrCode := o.Code
	qCode := qrCode
	if qCode != "" {

		if err := r.SetQueryParam("code", qCode); err != nil {
			return err
		}
	}

	if o.Error != nil {

		// query param error
		var qrError string

		if o.Error != nil {
			qrError = *o.Error
		}
		qError := qrError
		if qError != "" {

			if err := r.SetQueryParam("error", qError); err != nil {
				return err
			}
		}
	}

	// path param provider
	if err := r.SetPathParam("provider", o.Provider); err != nil {
		return err
	}

	// query param state
	qrState := o.State
	qState := qrState
	if qState != "" {

		if err := r.SetQueryParam("state", qState); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
