// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewOauthProvidersParams creates a new OauthProvidersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewOauthProvidersParams() *OauthProvidersParams {
	return &OauthProvidersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewOauthProvidersParamsWithTimeout creates a new OauthProvidersParams object
// with the ability to set a timeout on a request.
func NewOauthProvidersParamsWithTimeout(timeout time.Duration) *OauthProvidersParams {
	return &OauthProvidersParams{
		timeout: timeout,
	}
}

// NewOauthProvidersParamsWithContext creates a new OauthProvidersParams object
// with the ability to set a context for a request.
func NewOauthProvidersParamsWithContext(ctx context.Context) *OauthProvidersParams {
	return &OauthProvidersParams{
		Context: ctx,
	}
}

// NewOauthProvidersParamsWithHTTPClient creates a new OauthProvidersParams object
// with the ability to set a custom HTTPClient for a request.
func NewOauthProvidersParamsWithHTTPClient(client *http.Client) *OauthProvidersParams {
	return &OauthProvidersParams{
		HTTPClient: client,
	}
}

/*
OauthProvidersParams contains all the parameters to send to the API endpoint

	for the oauth providers operation.

	Typically these are written to a http.Request.
*/
type OauthProvidersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the oauth providers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OauthProvidersParams) WithDefaults() *OauthProvidersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the oauth providers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OauthProvidersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the oauth providers params
func (o *OauthProvidersParams) WithTimeout(timeout time.Duration) *OauthProvidersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the oauth providers params
func (o *OauthProvidersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the oauth providers params
func (o *OauthProvidersParams) WithContext(ctx context.Context) *OauthProvidersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the oauth providers params
func (o *OauthProvidersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the oauth providers params
func (o *OauthProvidersParams) WithHTTPClient(client *http.Client) *OauthProvidersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the oauth providers params
func (o *OauthProvidersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *OauthProvidersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
