// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// OauthAuthorizeReader is a Reader for the OauthAuthorize structure.
type OauthAuthorizeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OauthAuthorizeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 302:
		result := NewOauthAuthorizeFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 400:
		result := NewOauthAuthorizeBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewOauthAuthorizeNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /oauth/{provider}/authorize] oauthAuthorize", response, response.Code())
	}
}

// NewOauthAuthorizeFound creates a OauthAuthorizeFound with default headers values
func NewOauthAuthorizeFound() *OauthAuthorizeFound {
	return &OauthAuthorizeFound{}
}

/*
OauthAuthorizeFound describes a response with status code 302, with default header values.

redirect to OAuth provider
*/
type OauthAuthorizeFound struct {
}

// IsSuccess returns true when this oauth authorize found response has a 2xx status code
func (o *OauthAuthorizeFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this oauth authorize found response has a 3xx status code
func (o *OauthAuthorizeFound) IsRedirect() bool {
	return true
}

// IsClientError returns true when this oauth authorize found response has a 4xx status code
func (o *OauthAuthorizeFound) IsClientError() bool {
	return false
}

// IsServerError returns true when this oauth authorize found response has a 5xx status code
func (o *OauthAuthorizeFound) IsServerError() bool {
	return false
}

// IsCode returns true when this oauth authorize found response a status code equal to that given
func (o *OauthAuthorizeFound) IsCode(code int) bool {
	return code == 302
}

// Code gets the status code for the oauth authorize found response
func (o *OauthAuthorizeFound) Code() int {
	return 302
}

func (o *OauthAuthorizeFound) Error() string {
	return fmt.Sprintf("[GET /oauth/{provider}/authorize][%d] oauthAuthorizeFound", 302)
}

func (o *OauthAuthorizeFound) String() string {
	return fmt.Sprintf("[GET /oauth/{provider}/authorize][%d] oauthAuthorizeFound", 302)
}

func (o *OauthAuthorizeFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewOauthAuthorizeBadRequest creates a OauthAuthorizeBadRequest with default headers values
func NewOauthAuthorizeBadRequest() *OauthAuthorizeBadRequest {
	return &OauthAuthorizeBadRequest{}
}

/*
OauthAuthorizeBadRequest describes a response with status code 400, with default header values.

invalid request
*/
type OauthAuthorizeBadRequest struct {
}

// IsSuccess returns true when this oauth authorize bad request response has a 2xx status code
func (o *OauthAuthorizeBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this oauth authorize bad request response has a 3xx status code
func (o *OauthAuthorizeBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this oauth authorize bad request response has a 4xx status code
func (o *OauthAuthorizeBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this oauth authorize bad request response has a 5xx status code
func (o *OauthAuthorizeBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this oauth authorize bad request response a status code equal to that given
func (o *OauthAuthorizeBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the oauth authorize bad request response
func (o *OauthAuthorizeBadRequest) Code() int {
	return 400
}

func (o *OauthAuthorizeBadRequest) Error() string {
	return fmt.Sprintf("[GET /oauth/{provider}/authorize][%d] oauthAuthorizeBadRequest", 400)
}

func (o *OauthAuthorizeBadRequest) String() string {
	return fmt.Sprintf("[GET /oauth/{provider}/authorize][%d] oauthAuthorizeBadRequest", 400)
}

func (o *OauthAuthorizeBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewOauthAuthorizeNotFound creates a OauthAuthorizeNotFound with default headers values
func NewOauthAuthorizeNotFound() *OauthAuthorizeNotFound {
	return &OauthAuthorizeNotFound{}
}

/*
OauthAuthorizeNotFound describes a response with status code 404, with default header values.

provider not found
*/
type OauthAuthorizeNotFound struct {
}

// IsSuccess returns true when this oauth authorize not found response has a 2xx status code
func (o *OauthAuthorizeNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this oauth authorize not found response has a 3xx status code
func (o *OauthAuthorizeNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this oauth authorize not found response has a 4xx status code
func (o *OauthAuthorizeNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this oauth authorize not found response has a 5xx status code
func (o *OauthAuthorizeNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this oauth authorize not found response a status code equal to that given
func (o *OauthAuthorizeNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the oauth authorize not found response
func (o *OauthAuthorizeNotFound) Code() int {
	return 404
}

func (o *OauthAuthorizeNotFound) Error() string {
	return fmt.Sprintf("[GET /oauth/{provider}/authorize][%d] oauthAuthorizeNotFound", 404)
}

func (o *OauthAuthorizeNotFound) String() string {
	return fmt.Sprintf("[GET /oauth/{provider}/authorize][%d] oauthAuthorizeNotFound", 404)
}

func (o *OauthAuthorizeNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
