// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OauthCallbackReader is a Reader for the OauthCallback structure.
type OauthCallbackReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OauthCallbackReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewOauthCallbackOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewOauthCallbackBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewOauthCallbackInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /oauth/{provider}/callback] oauthCallback", response, response.Code())
	}
}

// NewOauthCallbackOK creates a OauthCallbackOK with default headers values
func NewOauthCallbackOK() *OauthCallbackOK {
	return &OauthCallbackOK{}
}

/*
OauthCallbackOK describes a response with status code 200, with default header values.

authentication successful
*/
type OauthCallbackOK struct {
	Payload *OauthCallbackOKBody
}

// IsSuccess returns true when this oauth callback o k response has a 2xx status code
func (o *OauthCallbackOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this oauth callback o k response has a 3xx status code
func (o *OauthCallbackOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this oauth callback o k response has a 4xx status code
func (o *OauthCallbackOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this oauth callback o k response has a 5xx status code
func (o *OauthCallbackOK) IsServerError() bool {
	return false
}

// IsCode returns true when this oauth callback o k response a status code equal to that given
func (o *OauthCallbackOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the oauth callback o k response
func (o *OauthCallbackOK) Code() int {
	return 200
}

func (o *OauthCallbackOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /oauth/{provider}/callback][%d] oauthCallbackOK %s", 200, payload)
}

func (o *OauthCallbackOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /oauth/{provider}/callback][%d] oauthCallbackOK %s", 200, payload)
}

func (o *OauthCallbackOK) GetPayload() *OauthCallbackOKBody {
	return o.Payload
}

func (o *OauthCallbackOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(OauthCallbackOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewOauthCallbackBadRequest creates a OauthCallbackBadRequest with default headers values
func NewOauthCallbackBadRequest() *OauthCallbackBadRequest {
	return &OauthCallbackBadRequest{}
}

/*
OauthCallbackBadRequest describes a response with status code 400, with default header values.

authentication failed
*/
type OauthCallbackBadRequest struct {
}

// IsSuccess returns true when this oauth callback bad request response has a 2xx status code
func (o *OauthCallbackBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this oauth callback bad request response has a 3xx status code
func (o *OauthCallbackBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this oauth callback bad request response has a 4xx status code
func (o *OauthCallbackBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this oauth callback bad request response has a 5xx status code
func (o *OauthCallbackBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this oauth callback bad request response a status code equal to that given
func (o *OauthCallbackBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the oauth callback bad request response
func (o *OauthCallbackBadRequest) Code() int {
	return 400
}

func (o *OauthCallbackBadRequest) Error() string {
	return fmt.Sprintf("[GET /oauth/{provider}/callback][%d] oauthCallbackBadRequest", 400)
}

func (o *OauthCallbackBadRequest) String() string {
	return fmt.Sprintf("[GET /oauth/{provider}/callback][%d] oauthCallbackBadRequest", 400)
}

func (o *OauthCallbackBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewOauthCallbackInternalServerError creates a OauthCallbackInternalServerError with default headers values
func NewOauthCallbackInternalServerError() *OauthCallbackInternalServerError {
	return &OauthCallbackInternalServerError{}
}

/*
OauthCallbackInternalServerError describes a response with status code 500, with default header values.

internal server error
*/
type OauthCallbackInternalServerError struct {
}

// IsSuccess returns true when this oauth callback internal server error response has a 2xx status code
func (o *OauthCallbackInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this oauth callback internal server error response has a 3xx status code
func (o *OauthCallbackInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this oauth callback internal server error response has a 4xx status code
func (o *OauthCallbackInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this oauth callback internal server error response has a 5xx status code
func (o *OauthCallbackInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this oauth callback internal server error response a status code equal to that given
func (o *OauthCallbackInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the oauth callback internal server error response
func (o *OauthCallbackInternalServerError) Code() int {
	return 500
}

func (o *OauthCallbackInternalServerError) Error() string {
	return fmt.Sprintf("[GET /oauth/{provider}/callback][%d] oauthCallbackInternalServerError", 500)
}

func (o *OauthCallbackInternalServerError) String() string {
	return fmt.Sprintf("[GET /oauth/{provider}/callback][%d] oauthCallbackInternalServerError", 500)
}

func (o *OauthCallbackInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*
OauthCallbackOKBody oauth callback o k body
swagger:model OauthCallbackOKBody
*/
type OauthCallbackOKBody struct {

	// account token
	AccountToken string `json:"accountToken,omitempty"`

	// email
	Email string `json:"email,omitempty"`
}

// Validate validates this oauth callback o k body
func (o *OauthCallbackOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this oauth callback o k body based on context it is used
func (o *OauthCallbackOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *OauthCallbackOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *OauthCallbackOKBody) UnmarshalBinary(b []byte) error {
	var res OauthCallbackOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
