// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewOauthAuthorizeParams creates a new OauthAuthorizeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewOauthAuthorizeParams() *OauthAuthorizeParams {
	return &OauthAuthorizeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewOauthAuthorizeParamsWithTimeout creates a new OauthAuthorizeParams object
// with the ability to set a timeout on a request.
func NewOauthAuthorizeParamsWithTimeout(timeout time.Duration) *OauthAuthorizeParams {
	return &OauthAuthorizeParams{
		timeout: timeout,
	}
}

// NewOauthAuthorizeParamsWithContext creates a new OauthAuthorizeParams object
// with the ability to set a context for a request.
func NewOauthAuthorizeParamsWithContext(ctx context.Context) *OauthAuthorizeParams {
	return &OauthAuthorizeParams{
		Context: ctx,
	}
}

// NewOauthAuthorizeParamsWithHTTPClient creates a new OauthAuthorizeParams object
// with the ability to set a custom HTTPClient for a request.
func NewOauthAuthorizeParamsWithHTTPClient(client *http.Client) *OauthAuthorizeParams {
	return &OauthAuthorizeParams{
		HTTPClient: client,
	}
}

/*
OauthAuthorizeParams contains all the parameters to send to the API endpoint

	for the oauth authorize operation.

	Typically these are written to a http.Request.
*/
type OauthAuthorizeParams struct {

	// Provider.
	Provider string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the oauth authorize params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OauthAuthorizeParams) WithDefaults() *OauthAuthorizeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the oauth authorize params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OauthAuthorizeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the oauth authorize params
func (o *OauthAuthorizeParams) WithTimeout(timeout time.Duration) *OauthAuthorizeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the oauth authorize params
func (o *OauthAuthorizeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the oauth authorize params
func (o *OauthAuthorizeParams) WithContext(ctx context.Context) *OauthAuthorizeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the oauth authorize params
func (o *OauthAuthorizeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the oauth authorize params
func (o *OauthAuthorizeParams) WithHTTPClient(client *http.Client) *OauthAuthorizeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the oauth authorize params
func (o *OauthAuthorizeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProvider adds the provider to the oauth authorize params
func (o *OauthAuthorizeParams) WithProvider(provider string) *OauthAuthorizeParams {
	o.SetProvider(provider)
	return o
}

// SetProvider adds the provider to the oauth authorize params
func (o *OauthAuthorizeParams) SetProvider(provider string) {
	o.Provider = provider
}

// WriteToRequest writes these params to a swagger request
func (o *OauthAuthorizeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param provider
	if err := r.SetPathParam("provider", o.Provider); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
