// Code generated by go-swagger; DO NOT EDIT.

package rest_model_zrok

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OauthProvider oauth provider
//
// swagger:model oauthProvider
type OauthProvider struct {

	// allow registration
	AllowRegistration bool `json:"allowRegistration,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this oauth provider
func (m *OauthProvider) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this oauth provider based on context it is used
func (m *OauthProvider) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OauthProvider) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OauthProvider) UnmarshalBinary(b []byte) error {
	var res OauthProvider
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
