// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// OauthAuthorizeHandlerFunc turns a function with the right signature into a oauth authorize handler
type OauthAuthorizeHandlerFunc func(OauthAuthorizeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn OauthAuthorizeHandlerFunc) Handle(params OauthAuthorizeParams) middleware.Responder {
	return fn(params)
}

// OauthAuthorizeHandler interface for that can handle valid oauth authorize params
type OauthAuthorizeHandler interface {
	Handle(OauthAuthorizeParams) middleware.Responder
}

// NewOauthAuthorize creates a new http.Handler for the oauth authorize operation
func NewOauthAuthorize(ctx *middleware.Context, handler OauthAuthorizeHandler) *OauthAuthorize {
	return &OauthAuthorize{Context: ctx, Handler: handler}
}

/*
	OauthAuthorize swagger:route GET /oauth/{provider}/authorize account oauthAuthorize

Initiate OAuth authorization flow
*/
type OauthAuthorize struct {
	Context *middleware.Context
	Handler OauthAuthorizeHandler
}

func (o *OauthAuthorize) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewOauthAuthorizeParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
