// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openziti/zrok/rest_model_zrok"
)

// OauthProvidersOKCode is the HTTP code returned for type OauthProvidersOK
const OauthProvidersOKCode int = 200

/*
OauthProvidersOK list of OAuth providers

swagger:response oauthProvidersOK
*/
type OauthProvidersOK struct {

	/*
	  In: Body
	*/
	Payload []*rest_model_zrok.OauthProvider `json:"body,omitempty"`
}

// NewOauthProvidersOK creates OauthProvidersOK with default headers values
func NewOauthProvidersOK() *OauthProvidersOK {

	return &OauthProvidersOK{}
}

// WithPayload adds the payload to the oauth providers o k response
func (o *OauthProvidersOK) WithPayload(payload []*rest_model_zrok.OauthProvider) *OauthProvidersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the oauth providers o k response
func (o *OauthProvidersOK) SetPayload(payload []*rest_model_zrok.OauthProvider) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *OauthProvidersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*rest_model_zrok.OauthProvider, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
