// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OauthCallbackHandlerFunc turns a function with the right signature into a oauth callback handler
type OauthCallbackHandlerFunc func(OauthCallbackParams) middleware.Responder

// Handle executing the request and returning a response
func (fn OauthCallbackHandlerFunc) Handle(params OauthCallbackParams) middleware.Responder {
	return fn(params)
}

// OauthCallbackHandler interface for that can handle valid oauth callback params
type OauthCallbackHandler interface {
	Handle(OauthCallbackParams) middleware.Responder
}

// NewOauthCallback creates a new http.Handler for the oauth callback operation
func NewOauthCallback(ctx *middleware.Context, handler OauthCallbackHandler) *OauthCallback {
	return &OauthCallback{Context: ctx, Handler: handler}
}

/*
	OauthCallback swagger:route GET /oauth/{provider}/callback account oauthCallback

OAuth callback handler
*/
type OauthCallback struct {
	Context *middleware.Context
	Handler OauthCallbackHandler
}

func (o *OauthCallback) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewOauthCallbackParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// OauthCallbackOKBody oauth callback o k body
//
// swagger:model OauthCallbackOKBody
type OauthCallbackOKBody struct {

	// account token
	AccountToken string `json:"accountToken,omitempty"`

	// email
	Email string `json:"email,omitempty"`
}

// Validate validates this oauth callback o k body
func (o *OauthCallbackOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this oauth callback o k body based on context it is used
func (o *OauthCallbackOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *OauthCallbackOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *OauthCallbackOKBody) UnmarshalBinary(b []byte) error {
	var res OauthCallbackOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
