// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// OauthCallbackOKCode is the HTTP code returned for type OauthCallbackOK
const OauthCallbackOKCode int = 200

/*
OauthCallbackOK authentication successful

swagger:response oauthCallbackOK
*/
type OauthCallbackOK struct {

	/*
	  In: Body
	*/
	Payload *OauthCallbackOKBody `json:"body,omitempty"`
}

// NewOauthCallbackOK creates OauthCallbackOK with default headers values
func NewOauthCallbackOK() *OauthCallbackOK {

	return &OauthCallbackOK{}
}

// WithPayload adds the payload to the oauth callback o k response
func (o *OauthCallbackOK) WithPayload(payload *OauthCallbackOKBody) *OauthCallbackOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the oauth callback o k response
func (o *OauthCallbackOK) SetPayload(payload *OauthCallbackOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *OauthCallbackOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// OauthCallbackBadRequestCode is the HTTP code returned for type OauthCallbackBadRequest
const OauthCallbackBadRequestCode int = 400

/*
OauthCallbackBadRequest authentication failed

swagger:response oauthCallbackBadRequest
*/
type OauthCallbackBadRequest struct {
}

// NewOauthCallbackBadRequest creates OauthCallbackBadRequest with default headers values
func NewOauthCallbackBadRequest() *OauthCallbackBadRequest {

	return &OauthCallbackBadRequest{}
}

// WriteResponse to the client
func (o *OauthCallbackBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// OauthCallbackInternalServerErrorCode is the HTTP code returned for type OauthCallbackInternalServerError
const OauthCallbackInternalServerErrorCode int = 500

/*
OauthCallbackInternalServerError internal server error

swagger:response oauthCallbackInternalServerError
*/
type OauthCallbackInternalServerError struct {
}

// NewOauthCallbackInternalServerError creates OauthCallbackInternalServerError with default headers values
func NewOauthCallbackInternalServerError() *OauthCallbackInternalServerError {

	return &OauthCallbackInternalServerError{}
}

// WriteResponse to the client
func (o *OauthCallbackInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
