// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// OauthAuthorizeFoundCode is the HTTP code returned for type OauthAuthorizeFound
const OauthAuthorizeFoundCode int = 302

/*
OauthAuthorizeFound redirect to OAuth provider

swagger:response oauthAuthorizeFound
*/
type OauthAuthorizeFound struct {
}

// NewOauthAuthorizeFound creates OauthAuthorizeFound with default headers values
func NewOauthAuthorizeFound() *OauthAuthorizeFound {

	return &OauthAuthorizeFound{}
}

// WriteResponse to the client
func (o *OauthAuthorizeFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(302)
}

// OauthAuthorizeBadRequestCode is the HTTP code returned for type OauthAuthorizeBadRequest
const OauthAuthorizeBadRequestCode int = 400

/*
OauthAuthorizeBadRequest invalid request

swagger:response oauthAuthorizeBadRequest
*/
type OauthAuthorizeBadRequest struct {
}

// NewOauthAuthorizeBadRequest creates OauthAuthorizeBadRequest with default headers values
func NewOauthAuthorizeBadRequest() *OauthAuthorizeBadRequest {

	return &OauthAuthorizeBadRequest{}
}

// WriteResponse to the client
func (o *OauthAuthorizeBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// OauthAuthorizeNotFoundCode is the HTTP code returned for type OauthAuthorizeNotFound
const OauthAuthorizeNotFoundCode int = 404

/*
OauthAuthorizeNotFound provider not found

swagger:response oauthAuthorizeNotFound
*/
type OauthAuthorizeNotFound struct {
}

// NewOauthAuthorizeNotFound creates OauthAuthorizeNotFound with default headers values
func NewOauthAuthorizeNotFound() *OauthAuthorizeNotFound {

	return &OauthAuthorizeNotFound{}
}

// WriteResponse to the client
func (o *OauthAuthorizeNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
