// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// OauthProvidersHandlerFunc turns a function with the right signature into a oauth providers handler
type OauthProvidersHandlerFunc func(OauthProvidersParams) middleware.Responder

// Handle executing the request and returning a response
func (fn OauthProvidersHandlerFunc) Handle(params OauthProvidersParams) middleware.Responder {
	return fn(params)
}

// OauthProvidersHandler interface for that can handle valid oauth providers params
type OauthProvidersHandler interface {
	Handle(OauthProvidersParams) middleware.Responder
}

// NewOauthProviders creates a new http.Handler for the oauth providers operation
func NewOauthProviders(ctx *middleware.Context, handler OauthProvidersHandler) *OauthProviders {
	return &OauthProviders{Context: ctx, Handler: handler}
}

/*
	OauthProviders swagger:route GET /oauth/providers account oauthProviders

List available OAuth providers
*/
type OauthProviders struct {
	Context *middleware.Context
	Handler OauthProvidersHandler
}

func (o *OauthProviders) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewOauthProvidersParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
